server {
    listen 80;
    server_name ${NGINX_HOST};
    root /var/www/html/default;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        return 200;
    }
}

